### ISSUE TITLE
Double opt-in

### ISSUE THREAD

**Issue by WHITE-developer** [digitalpulsebe/craft-formie-flexmail#3]
If I follow the API documentation correctly, there are separate endpoints for [creating a contact](https://api.flexmail.eu/documentation/#post-/contacts) and creating a contact via [double opt-in](https://api.flexmail.eu/documentation/#post-/opt-ins).

In the plugin I see the normal create a contact endpoint is used.
Any plans to support the double opt-in endpoint?

**Comment by jodeba** [comment]
Hi @WHITE-developer , 

Great suggestion! We've put it on the feature list.

**Comment by WHITE-developer** [comment]
Hi @JodebaDigitalPulse 

Any idea when you want to implement it?

**Comment by jodeba** [comment]
Hi @WHITE-developer ,

I made a release for this (1.1.0 in Craft 4; 2.1.0 in Craft 5), so it will add an option in the sources list.

For example if your Opt-In form has the name _List_, it will show as: '**List (opt-in)**'
It might be confusing, because the API of Flexmail also returns the contact source 'opt-in-List', because they create this in the background. If you push contacts to that list, they show up as confirmed contacts.

**Comment by WHITE-developer** [comment]
Cool, thanks!

But I get an error, I think because the 'custom_fields' ends up completely empty in my case. Have to ask our client what the possible values are for the custom fields to see if it works with a value.

`API error: “{"errors":[{"message":"Invalid type array, expected object","constraint":"type","pointer":"\/custom_fields"}],"title":"Input validation failed","type":"\/documentation\/#validation-errors","status":400}” /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111  `

Removing the 'custom_fields' payload completely when it's empty did work for me
```php
if (sizeof($payload['custom_fields']) == 0) {
    unset($payload['custom_fields']);
}
```

**Comment by jodeba** [comment]
Hi,

thank you for the feedback. My bad, I didn't test that case.
I made a hotfix for that!

Best regards
